namespace Accounting
{
    public enum GroupErrorCodes
    {
        AccountSystem = 101,
        OrgUnit = 102,
        AccCase = 103,
        WorkPlace = 104,
        YearCategory = 105,
        MenuAccounting = 106,
        Career,
        Partner,
        ProductOrigin,
        Window,
        Tab,
        FProductWork,
        VoucherCategory,
        Warehouse,
        Product,
        AccOpeningBalance,
        AccVoucher,
        Reference,
        PartnerGroup,
        TenantSetting,
        Ledger,
        User,
        Role,
        BusinessCategory,
        TaxCategory,
        SaleChannel,
        Department,
        ProductGroup,
        ExciseTax,
        Contract,
        ProductLot,
        DiscountPrice,
        ProductionPeriod,
        Currency,
        Unit,
        VoucherType,
        PaymentTerm,
        InvoiceBook,
        FeeType,
        VoucherPaymentBook,
        AssetToolGroup,
        Purpose,
        Reason,
        Capital,
        AssetTool,
        AssetToolAccount,
        GroupCoefficient,
        AllotmentForwardCategory,
        FProductWorkNorm,
        ImportExcelTemplate,
        AccSection,
        RegLicense,
        InvoiceAuth,
        InvoiceSupplier,
        Tenant,
        CustomerRegister,
        InvoiceStatus,
        Position,
        Employee,
        SalaryPeriod,
        SalaryCategory,
        InventoryRecord,        
        ReportTemplate,
        IdentityUser,
        ProductVoucher,        
        Printing,
        Report,
        ExportXml,
        VoucherPaymentBeginning,
        Person
    }
}
